export const ACTIONS = {
  INIT: 'INIT',
  FETCH_VENUES: 'FETCH_VENUES',
  RECEIVE_VENUES: 'RECEIVE_VENUES',
  GEOLOCATION_FAILED: 'GEOLOCATION_FAILED',
  NETWORK_ERROR: 'NETWORK_ERROR',
  FETCH_GEODATA: 'FETCH_GEODATA',
  RECEIVE_GEODATA: 'RECEIVE_GEODATA',
};
